# -*- coding: utf-8 -*-
"""iris classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEK9My0Lye4tCe1ZGx-5T1lHXUMtTj96
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
# %matplotlib inline

from google.colab import drive

data = pd.read_csv('/content/Iris.csv')

data.head()

data.columns = ["id","slen","swid","plen","pwid","target"]

data.head()

data.describe()

sns.pairplot(data,hue="target")

plt.hist(data["slen"],bins=25);

data

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

X = data.drop(["target"],axis=1)

y = data['target']

X

y

scaler = ss.fit(X)

X_stdscaler = scaler.transform(X)

X_stdscaler

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

#logistic regression
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X_train,y_train)

prediction = LR.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction)*100)

from sklearn.metrics import classification_report
print(classification_report(y_test,prediction))