# -*- coding: utf-8 -*-
"""unemployment analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OP7MEfng7AJFkrTqpM5gKPWaUF5KpDft
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import plotly.express as px
# %matplotlib inline

data = pd.read_csv('/content/Unemployment in India.csv')

data.head()

data.sample(8)

data.shape



print(data.isnull().sum())

data.describe()

data.info()

data.info

data.duplicated().sum()

data.dtypes

plt.style.use('seaborn-whitegrid')
plt.show()

x = data['Region']

x

y = data[' Estimated Unemployment Rate (%)']

y

seconddata=data.iloc[:,3]

seconddata

fg = px.bar(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment Rate',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total ascending'})
fg.show()

fg = px.box(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment Rate',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.scatter(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment Rate',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.histogram(data,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',title='Unemployment Rate',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()